"""change_col_names

Revision ID: 51638969e8e9
Revises: f0ad6829f426
Create Date: 2025-12-14 13:51:20.335734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51638969e8e9"
down_revision: Union[str, Sequence[str], None] = "f0ad6829f426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entries",
        sa.Column("encrypted_markdown", sa.String(), nullable=True),
        schema="journal",
    )
    op.drop_column("entries", "raw_markdown", schema="journal")
    op.add_column(
        "metrics",
        sa.Column("paid_productivity", sa.Float(), nullable=True),
        schema="journal",
    )
    op.add_column(
        "metrics",
        sa.Column("personal_productivity", sa.Float(), nullable=True),
        schema="journal",
    )
    op.drop_column("metrics", "hours_personal_work", schema="journal")
    op.drop_column("metrics", "hours_paid_work", schema="journal")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics",
        sa.Column(
            "hours_paid_work",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="journal",
    )
    op.add_column(
        "metrics",
        sa.Column(
            "hours_personal_work",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="journal",
    )
    op.drop_column("metrics", "personal_productivity", schema="journal")
    op.drop_column("metrics", "paid_productivity", schema="journal")
    op.add_column(
        "entries",
        sa.Column("raw_markdown", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="journal",
    )
    op.drop_column("entries", "encrypted_markdown", schema="journal")
    # ### end Alembic commands ###
