"""written_at_entries_col

Revision ID: df763d95c88d
Revises: 7079ea392a1f
Create Date: 2025-12-15 11:27:18.684792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df763d95c88d"
down_revision: Union[str, Sequence[str], None] = "7079ea392a1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entries",
        sa.Column("written_at", sa.DateTime(timezone=True), nullable=True),
        schema="journal",
    )

    op.execute(
        """
        UPDATE journal.entries
        SET written_at = created_at
        """
    )

    op.alter_column(
        "entries",
        "written_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        schema="journal",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "written_at", schema="journal")
    # ### end Alembic commands ###
