"""out_of_bed_at_timestamp

Revision ID: ea3feb93b5be
Revises: df763d95c88d
Create Date: 2026-01-03 14:34:44.887044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3feb93b5be'
down_revision: Union[str, Sequence[str], None] = 'df763d95c88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('out_of_bed_at', sa.DateTime(timezone=True), nullable=True), schema='journal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'out_of_bed_at', schema='journal')
    # ### end Alembic commands ###
