"""adapt users tbl

Revision ID: f0ad6829f426
Revises: f5daa82943ab
Create Date: 2025-11-22 14:48:59.981773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0ad6829f426"
down_revision: Union[str, Sequence[str], None] = "f5daa82943ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True), schema="core")
    op.add_column(
        "users", sa.Column("picture", sa.String(), nullable=True), schema="core"
    )
    op.create_unique_constraint(
        "uq_users_external_auth_sub_email",
        "users",
        ["external_auth_sub", "email"],
        schema="core",
    )
    op.create_unique_constraint(
        "uq_users_external_auth_sub", "users", ["external_auth_sub"], schema="core"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_external_auth_sub", "users", schema="core", type_="unique"
    )
    op.drop_constraint(
        "uq_users_external_auth_sub_email", "users", schema="core", type_="unique"
    )
    op.drop_column("users", "picture", schema="core")
    op.drop_column("users", "name", schema="core")
    # ### end Alembic commands ###
