"""initital migration

Revision ID: f5daa82943ab
Revises:
Create Date: 2025-11-16 18:33:19.855013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5daa82943ab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS journal")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("external_auth_sub", sa.String(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="core",
    )
    op.create_table(
        "threads",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["core.users.id"], name="core_user_fk"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_threads_user_id_date"),
        schema="journal",
    )
    op.create_table(
        "entries",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("raw_markdown", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["journal.threads.id"], name="journal_thread_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="journal",
    )
    op.create_table(
        "metrics",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("asleep_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("awoke_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sleep_quality", sa.Float(), nullable=True),
        sa.Column("physical_activity", sa.Float(), nullable=True),
        sa.Column("overall_mood", sa.Float(), nullable=True),
        sa.Column("hours_paid_work", sa.Float(), nullable=True),
        sa.Column("hours_personal_work", sa.Float(), nullable=True),
        sa.Column(
            "additional_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["journal.threads.id"], name="journal_thread_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
        schema="journal",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metrics", schema="journal")
    op.drop_table("entries", schema="journal")
    op.drop_table("threads", schema="journal")
    op.drop_table("users", schema="core")
    # ### end Alembic commands ###
